### ISSUE TITLE
OAuth Error help?

### ISSUE THREAD

**Issue by micahstubbs** [KaiDalgleish/moodometer#1]
followed the instructions in the `README.md` and hit this OAuth error:

```
OAuth Error: redirect_uri did not match any configured URIs.

Passed URI : http://localhost:5000/slacked
Allowed URI : http://127.0.0.1:5000/slacked
Allowed URI : https://127.0.0.1:5000/slacked
```

**Comment by KaiBot3000** [comment]
Hey Micah- Have you tried changing the URI to use `127.0.0.1` instead of `localhost`? I would try that, and if it doesn't work, try changing the redirect URI in Slack. I haven't tried running this in a while so you might have to debug it a little :)

**Comment by micahstubbs** [comment]
hi @KaiBot3000, thanks for the suggestions.  just went back to try this again.  it looks like both of those are in place.  here is what I see in the browser:

![screen shot 2016-08-12 at 1 27 17 am](https://cloud.githubusercontent.com/assets/2119400/17616931/0304cbcc-602c-11e6-93ab-c3dc2f9c15b9.png)

and here is what I see in the slack app config UI:

![screen shot 2016-08-12 at 1 27 25 am](https://cloud.githubusercontent.com/assets/2119400/17616937/1176f202-602c-11e6-92fd-eaf70f27eed4.png)

**Comment by micahstubbs** [comment]
figured it out!  PR ^^ 🎉

**Comment by micahstubbs** [comment]
not a big deal, but if I remember right, changing the url in the browser didn't solve it for me with latest Chrome.  will leave a comment here just in case others experience this later on.

**Comment by avinashr409** [comment]
Hi, I'm facing the same issue.
where should I change the redirecr uri?

**Comment by micahstubbs** [comment]
@avinashr409 this change worked for me 😄 https://github.com/KaiBot3000/slackometer/pull/2/files#diff-d355af669766ee3562643e8e5034f715R35

**Comment by micahstubbs** [comment]
`"redirect_uri": "http://127.0.0.1:5000/slacked",`
